name: .Net Build SqlServerQueryHelper

on:
  push:
    paths: 
      - 'src/SqlServerQueryHelper/**'
  pull_request:
    paths: 
      - 'src/SqlServerQueryHelper/**'
  workflow_dispatch:
  
jobs:
  build:

    defaults: 
      run:
        working-directory: src/SqlServerQueryHelper
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100

    - name: Test
      run: dotnet test SqlServerQueryHelper.Tests/SqlServerQueryHelper.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Build
      run: dotnet build --configuration Release 

    - name: Upload SqlServerQueryHelper
      uses: actions/upload-artifact@v4
      with:
        name: SqlServerQueryHelper
        path: src/SqlServerQueryHelper/SqlServerQueryHelper/bin/Release/*.nupkg

    - name: Upload SqlServerQueryHelper.EntityFrameworkCore.SqlServer
      uses: actions/upload-artifact@v4
      with:
        name: SqlServerQueryHelper.EntityFrameworkCore
        path: src/SqlServerQueryHelper/SqlServerQueryHelper.EntityFrameworkCore/bin/Release/*.nupkg
